version: "2.4"
services:
  stage-1:
    build:
      context: .
    privileged: true
    environment:
      MIRROR_HOST: http://mirrors.ustc.edu.cn/debian/
      IMAGE_FILE: disk.stage-1.qcow2
      STAGE_NAME: stage-1
    volumes:
      - $PWD:/workspace
      - $PWD/scripts/debian:/scripts
    working_dir: /workspace
    command:
      - bash
      -   /scripts/entrypoint.sh
  stage-2:
    build:
      context: .
    privileged: true
    environment:
      BASE_IMAGE: disk.stage-1.qcow2
      IMAGE_FILE: disk.stage-2.qcow2
      STAGE_NAME: stage-2
    volumes:
      - $PWD:/workspace
      - $PWD/scripts/debian:/scripts
    working_dir: /workspace
    command:
      - bash
      -   /scripts/entrypoint.sh
  stage-3:
    build:
      context: .
    privileged: true
    environment:
      BASE_IMAGE: disk.stage-2.qcow2
      IMAGE_FILE: disk.stage-3.qcow2
      STAGE_NAME: stage-3
    volumes:
      - $PWD:/workspace
      - $PWD/scripts/debian:/scripts
    working_dir: /workspace
    command:
      - bash
      -   /scripts/entrypoint.sh
  stage-end:
    build:
      context: .
    privileged: true
    environment:
      BASE_IMAGE: disk.stage-3.qcow2
      IMAGE_FILE: disk.qcow2
      STAGE_NAME: stage-end
    volumes:
      - $PWD:/workspace
      - $PWD/scripts/debian:/scripts
    working_dir: /workspace
    command:
      - bash
      -   /scripts/entrypoint.sh
  generate-ova:
    build:
      context: .
    privileged: true
    environment:
      IMAGE_FILE: disk.qcow2
    volumes:
      - $PWD:/workspace
      - $PWD/scripts/debian:/scripts
    working_dir: /workspace
    command:
      - bash
      -   /scripts/generate-ova.sh
      -     Debian
