version: "2.4"
services:
  stage-1: &base
    build:
      context: .
    privileged: true
    environment:
      STAGE_NAME: stage-1
      IMAGE_FILE: disk.stage-1.qcow2
      MIRROR_HOST: http://mirrors.ustc.edu.cn/debian/
    volumes:
      - $PWD/.disks:/workspace
      - $PWD/scripts/debian:/scripts:ro
    working_dir: /workspace
    command:
      - bash
      -   /scripts/entrypoint.sh
  stage-2:
    <<: *base
    environment:
      STAGE_NAME: stage-2
      BASE_IMAGE: disk.stage-1.qcow2
      IMAGE_FILE: disk.stage-2.qcow2
  stage-3:
    <<: *base
    environment:
      STAGE_NAME: stage-3
      BASE_IMAGE: disk.stage-2.qcow2
      IMAGE_FILE: disk.stage-3.qcow2
  stage-end:
    <<: *base
    environment:
      STAGE_NAME: stage-end
      BASE_IMAGE: disk.stage-3.qcow2
      IMAGE_FILE: disk.qcow2
  generate-ova:
    <<: *base
    environment:
      IMAGE_FILE: disk.qcow2
    command:
      - bash
      -   /scripts/generate-ova.sh
      -     Debian
