{{ $distro := (ds "distro") -}}
{{ $pipelines := ($distro.pipelines | coll.Sort "order") -}}
version: "2.4"
services:
  _base: &base
    image: {{ $distro.builder }}
    privileged: true
    environment:
      DISTRO_NAME: {{ $distro.name }}
    volumes:
      - $PWD/{{ $distro.dirs.disks }}:/workspace
      - $PWD/{{ $distro.dirs.artifacts }}:/{{ $distro.dirs.artifacts }}
      - $PWD/distro/common:/scripts/common:ro
      {{- range $pipeline := $pipelines }}
      - $PWD/distro/{{ $distro.name }}/{{ $pipeline.name }}:/scripts/pipelines/{{ $pipeline.name }}:ro
      {{- end }}
    working_dir: /workspace
    command:
      - bash
      -   /scripts/common/job.sh

#===============================================================================
# Pipelines
{{- range $pn, $pipeline := $pipelines }}
  {{- $prevPipeline := (index $pipelines 0) }}
  {{- if ne $pn 0 }}
  {{- $prevPipeline = (index $pipelines (math.Sub $pn 1)) }}
  {{- end }}
  {{- $items := $pipeline.items | coll.Sort }}
  #======================================
  # pipeline - {{ $pipeline.name }}
  pipeline-{{ $pipeline.name }}:
    <<: *base
    environment:
      DISTRO_NAME: {{ $distro.name }}
      PIPELINE_NAME: {{ $pipeline.name }}
      {{- if eq $pn 0 }}
      ROOT_PIPELINE: "1"
      {{- else }}
      BASE_IMAGE: pipeline.{{ $prevPipeline.name }}.qcow2
      {{- end }}
      IMAGE_FILE: pipeline.{{ $pipeline.name }}.qcow2
    command:
      - bash
      -   /scripts/common/pipeline.sh
  {{- range $n, $name := $items }}
  {{ $pipeline.name }}-{{ $name }}:
    <<: *base
    environment:
      DISTRO_NAME: {{ $distro.name }}
      MIRROR_HOST: {{ index $distro.mirrors $distro.name }}
      PIPELINE_NAME: {{ $pipeline.name }}
      PIPELINE_JOB: {{ $name }}
      {{- if $pipeline.chroot }}
      CHROOT: "1"
      {{- end }}
      IMAGE_FILE: pipeline.{{ $pipeline.name }}.qcow2
  {{- end }}
{{- end }}


#===============================================================================
# artifacts
  artifact-vmdk:
    <<: *base
    environment:
      DISTRO_NAME: {{ $distro.name }}
      {{- $lastPipeline := (index $pipelines (math.Sub (len $pipelines) 1)) }}
      IMAGE_FILE: pipeline.{{ $lastPipeline.name }}.qcow2
      TARGET_FILE: /{{ $distro.dirs.artifacts }}/{{ $distro.name }}.vmdk
      ARTIFACT_DIR: /{{ $distro.dirs.artifacts }}
    command:
      - bash
      -   /scripts/common/artifact-vmdk.sh
  artifact-ova:
    <<: *base
    environment:
      DISTRO_NAME: {{ $distro.name }}
      IMAGE_FILE: /{{ $distro.dirs.artifacts }}/{{ $distro.name }}.vmdk
      TARGET_FILE: /{{ $distro.dirs.artifacts }}/{{ $distro.name }}.ova
      ARTIFACT_DIR: /{{ $distro.dirs.artifacts }}
    command:
      - bash
      -   /scripts/common/artifact-ova.sh
