{{ $distro := (ds "distro") -}}
{{ $pipelines := ($distro.pipelines | coll.Sort "index") -}}
version: "2.4"
services:
  _base: &base
    image: {{ $distro.builder }}
    privileged: true
    environment:
      DISTRO_NAME: {{ $distro.name }}
      MIRROR_HOST: http://mirrors.ustc.edu.cn/debian/
    volumes:
      - $PWD/{{ $distro.dirs.disks }}:/workspace
      - $PWD/{{ $distro.dirs.artifacts }}:/{{ $distro.dirs.artifacts }}
      - $PWD/distro/common:/scripts/common:ro
      - $PWD/distro/{{ $distro.name }}/stages:/scripts/stages:ro
    working_dir: /workspace
    command:
      - bash
      -   /scripts/common/entrypoint.sh

#===============================================================================
# Pipelines
{{- range $pn, $pipeline := $pipelines }}
  {{- $items := $pipeline.items | coll.Sort }}
  #======================================
  # pipeline - {{ $pipeline.name }}
  pipeline-{{ $pipeline.name }}:
    <<: *base
    environment:
      DISTRO_NAME: {{ $distro.name }}
      STAGE_NAME: pipeline-{{ $pipeline.name }}
      {{- $lastItemIndex := math.Sub (len $items) 1 }}
      BASE_IMAGE: pipeline.{{ $pipeline.name }}.{{ index $items $lastItemIndex }}.qcow2
      IMAGE_FILE: pipeline.{{ $pipeline.name }}.qcow2
  {{- range $n, $name := $items }}
  {{ $pipeline.name }}-{{ $name }}:
    <<: *base
    environment:
      DISTRO_NAME: {{ $distro.name }}
      STAGE_NAME: {{ $name }}
      {{- if and (eq $n 0) (ne $pn 0) }}
      {{- $prevPipeline := (index $pipelines (math.Sub $pn 1)) }}
      BASE_IMAGE: pipeline.{{ $prevPipeline.name }}.qcow2
      {{- else if ne $n 0 }}
      {{- $prevItemIndex := math.Sub $n 1 }}
      BASE_IMAGE: pipeline.{{ $pipeline.name }}.{{ index $items $prevItemIndex }}.qcow2
      {{- end }}
      IMAGE_FILE: pipeline.{{ $pipeline.name }}.{{ $name }}.qcow2
  {{- end }}
{{- end }}


#===============================================================================
# artifacts
  artifact-vmdk:
    <<: *base
    environment:
      DISTRO_NAME: {{ $distro.name }}
      {{- $lastPipeline := (index $pipelines (math.Sub (len $pipelines) 1)) }}
      IMAGE_FILE: pipeline.{{ $lastPipeline.name }}.qcow2
      TARGET_FILE: /{{ $distro.dirs.artifacts }}/{{ $distro.name }}.vmdk
      ARTIFACT_DIR: /{{ $distro.dirs.artifacts }}
    command:
      - bash
      -   /scripts/common/artifact-vmdk.sh
  artifact-ova:
    <<: *base
    environment:
      DISTRO_NAME: {{ $distro.name }}
      IMAGE_FILE: /{{ $distro.dirs.artifacts }}/{{ $distro.name }}.vmdk
      TARGET_FILE: /{{ $distro.dirs.artifacts }}/{{ $distro.name }}.ova
      ARTIFACT_DIR: /{{ $distro.dirs.artifacts }}
    command:
      - bash
      -   /scripts/common/artifact-ova.sh
