{{ $distro := (ds "distro") -}}
{{ $pipelines := ($distro.pipelines | coll.Sort "order") -}}
{{ $lastPipeline := (index $pipelines (math.Sub (len $pipelines) 1)) -}}
{{ $editions := $distro.editions -}}
version: "2.4"
services:
  _base: &base
    image: {{ $distro.builder }}
    privileged: true
    environment:
      DISTRO_NAME: {{ $distro.name }}
    volumes:
      - $PWD/{{ $distro.dirs.disks }}:/workspace
      - $PWD/{{ $distro.dirs.artifacts }}:/{{ $distro.dirs.artifacts }}
      - $PWD/common:/scripts/common:ro
      {{- range $pipeline := $pipelines }}
      - $PWD/distro/{{ $distro.name }}/{{ $pipeline.name }}:/scripts/pipelines/{{ $pipeline.name }}:ro
      {{- end }}
      {{- range $edition := $editions }}
      - $PWD/distro/{{ $distro.name }}/@edition/{{ $edition.name }}:/scripts/pipelines/@{{ $edition.name }}:ro
      {{- end }}
    working_dir: /workspace
    command:
      - bash
      -   /scripts/common/job.sh

#===============================================================================
# Pipelines
{{- range $pn, $pipeline := $pipelines }}
  {{- $prevPipeline := (index $pipelines 0) }}
  {{- if ne $pn 0 }}
  {{- $prevPipeline = (index $pipelines (math.Sub $pn 1)) }}
  {{- end }}
  {{- $items := $pipeline.items | coll.Sort }}
  #======================================
  # pipeline - {{ $pipeline.name }}
  pipeline-{{ $pipeline.name }}:
    <<: *base
    environment:
      DISTRO_NAME: {{ $distro.name }}
      DEVID: {{ $distro.devid }}
      PIPELINE_NAME: {{ $pipeline.name }}
      {{- if eq $pn 0 }}
      ROOT_PIPELINE: "1"
      {{- else }}
      BASE_IMAGE: pipeline.{{ $prevPipeline.name }}.qcow2
      {{- end }}
      IMAGE_FILE: pipeline.{{ $pipeline.name }}.qcow2
      {{- range $k, $v := $distro.environment }}
      {{ $k }}: "{{ $v }}"
      {{- end }}
    command:
      - bash
      -   /scripts/common/pipeline.sh
  {{- range $n, $name := $items }}
  {{ $pipeline.name }}-{{ $name }}:
    <<: *base
    environment:
      DISTRO_NAME: {{ $distro.name }}
      DEVID: {{ $distro.devid }}
      PIPELINE_NAME: {{ $pipeline.name }}
      PIPELINE_JOB: {{ $name }}
      {{- if $pipeline.chroot }}
      CHROOT: "1"
      {{- end }}
      {{- if coll.Has $pipeline "shell" }}
      CHROOT_SHELL: "{{ $pipeline.shell }}"
      {{- else }}
      CHROOT_SHELL: "bash"
      {{- end }}
      IMAGE_FILE: pipeline.{{ $pipeline.name }}.qcow2
      {{- range $k, $v := $distro.environment }}
      {{ $k }}: "{{ $v }}"
      {{- end }}
  {{- end }}
{{- end }}

#===============================================================================
# Editions
{{- range $pn, $edition := $editions }}
  {{- $items := $edition.items | coll.Sort }}
  #======================================
  # Edition - {{ $edition.name }}
  edition-{{ $edition.name }}:
    <<: *base
    environment:
      DISTRO_NAME: {{ $distro.name }}
      DEVID: {{ $distro.devid }}
      PIPELINE_NAME: "@{{ $edition.name }}"
      BASE_IMAGE: pipeline.{{ $lastPipeline.name }}.qcow2
      IMAGE_FILE: edition.{{ $edition.name }}.qcow2
      {{- range $k, $v := $distro.environment }}
      {{ $k }}: "{{ $v }}"
      {{- end }}
    command:
      - bash
      -   /scripts/common/pipeline.sh
  {{- range $n, $name := $items }}
  edition-{{ $edition.name }}-{{ $name }}:
    <<: *base
    environment:
      DISTRO_NAME: {{ $distro.name }}
      DEVID: {{ $distro.devid }}
      PIPELINE_NAME: "@{{ $edition.name }}"
      PIPELINE_JOB: {{ $name }}
      CHROOT: "1"
      {{- if coll.Has $edition "shell" }}
      CHROOT_SHELL: "{{ $edition.shell }}"
      {{- else }}
      CHROOT_SHELL: "sh"
      {{- end }}
      IMAGE_FILE: edition.{{ $edition.name }}.qcow2
      {{- range $k, $v := $distro.environment }}
      {{ $k }}: "{{ $v }}"
      {{- end }}
  {{- end }}
{{- end }}

#===============================================================================
# artifacts
  artifact-vmdk:
    <<: *base
    environment:
      DISTRO_NAME: {{ $distro.name }}
      DEVID: {{ $distro.devid }}
      IMAGE_FILE: pipeline.{{ $lastPipeline.name }}.qcow2
      TARGET_FILE: /{{ $distro.dirs.artifacts }}/{{ $distro.name }}-{{ $distro.environment.DISTRO_VER }}.vmdk
      ARTIFACT_DIR: /{{ $distro.dirs.artifacts }}
    command:
      - bash
      -   /scripts/common/artifact-vmdk.sh
  artifact-ova:
    <<: *base
    environment:
      DISTRO_NAME: {{ $distro.name }}
      DEVID: {{ $distro.devid }}
      IMAGE_FILE: /{{ $distro.dirs.artifacts }}/{{ $distro.name }}-{{ $distro.environment.DISTRO_VER }}.vmdk
      TARGET_FILE: /{{ $distro.dirs.artifacts }}/{{ $distro.name }}-{{ $distro.environment.DISTRO_VER }}.ova
      ARTIFACT_DIR: /{{ $distro.dirs.artifacts }}
    command:
      - bash
      -   /scripts/common/artifact-ova.sh
  artifact-ova-upload:
    <<: *base
    environment:
      DISTRO_NAME: {{ $distro.name }}
      DEVID: {{ $distro.devid }}
      TARGET_FILE: /{{ $distro.dirs.artifacts }}/{{ $distro.name }}.ova
      ARTIFACT_DIR: /{{ $distro.dirs.artifacts }}
    command:
      - bash
      -   /scripts/common/artifact-upload.sh

{{- range $distro.editions }}
#===============================================================================
# artifacts@{{ .name }}
  artifact-vmdk.{{ .name }}:
    <<: *base
    environment:
      DISTRO_NAME: {{ $distro.name }}
      DEVID: {{ $distro.devid }}
      IMAGE_FILE: edition.{{ .name }}.qcow2
      TARGET_FILE: /{{ $distro.dirs.artifacts }}/{{ $distro.name }}-{{ $distro.environment.DISTRO_VER }}@{{ .name }}.vmdk
      ARTIFACT_DIR: /{{ $distro.dirs.artifacts }}
      {{- range $k, $v := $distro.environment }}
      {{ $k }}: "{{ $v }}"
      {{- end }}
    command:
      - bash
      -   /scripts/common/artifact-vmdk.sh
  artifact-ova.{{ .name }}:
    <<: *base
    environment:
      DISTRO_NAME: {{ $distro.name }}
      DEVID: {{ $distro.devid }}
      IMAGE_FILE: /{{ $distro.dirs.artifacts }}/{{ $distro.name }}-{{ $distro.environment.DISTRO_VER }}@{{ .name }}.vmdk
      TARGET_FILE: /{{ $distro.dirs.artifacts }}/{{ $distro.name }}-{{ $distro.environment.DISTRO_VER }}@{{ .name }}.ova
      ARTIFACT_DIR: /{{ $distro.dirs.artifacts }}
      {{- range $k, $v := $distro.environment }}
      {{ $k }}: "{{ $v }}"
      {{- end }}
    command:
      - bash
      -   /scripts/common/artifact-ova.sh
{{- end }}
