name: centos-builder
on:
  push:
    paths:
      - '.github/workflows/builder-centos.yml'
      - 'distro/centos/Dockerfile'
  schedule:
    - cron: '0 0 1 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CI_REGISTRY: docker.pkg.github.com

jobs:
  make-builder:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build-and-push-builder-image
      run: |
        make centos:builder
        make centos:builder-push
