name: debian
on:
  push:
    branches:
      - master
    paths:
      - '!distro/debian/Dockerfile'
      - '.github/workflows/*-debian.yml'
      - 'common/**'
      - 'templates/**'
      - 'distro/debian/**'
  schedule:
    - cron: '0 8 1 * *'

env:
  CI_REGISTRY: docker.pkg.github.com

jobs:
  build-artifacts:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build-artifacts
      run: |
        # nbd driver is required
        sudo modprobe nbd
        make debian:build
        make debian:artifacts
        sudo chmod 444 artifacts/*
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      if: ${{ env.GITHUB_EVENT_NAME == 'schedule' }}
      with:
        name: debian-artifact
        path: artifacts/debian.ova
