name: debian
on:
  push:
    branches:
      - master
    paths:
      - '!.github/workflows/builder-*'
      - '!distro/debian/Dockerfile'
      - '.github/workflows/*-debian.yml'
      - 'common/**'
      - 'templates/**'
      - 'distro/debian/**'
  schedule:
    - cron: '0 8 1 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CI_REGISTRY: docker.pkg.github.com

jobs:
  build-artifacts:
    runs-on: ubuntu-24.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build-artifacts
      run: |
        # nbd driver is required
        sudo modprobe nbd
        make debian:build
        make debian:artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
      with:
        name: debian-artifact
        path: .build/artifacts/*.ova
